# Overwrites the /sk command for certain arguments.
# So if you do /sk info it runs /skp info, but commands like /sk reload are untouched.
# Recommended value: true
overwrite-command: true

update-checker:
  # Whether the update checker will run on an interval.
  # If disabled, you must run /sk check whenever you want to update the cache.
  run-on-interval: false

  # To prevent request spam, all update checks are done once in a while then cached (and on server start).
  # This setting determines the interval (in minutes) between update checks.
  # Recommended value: 1440 (24 hours)
  interval: 1440

  # Logs a console message whenever the update checker is ran.
  log-messages: true

  # Timeout (in seconds) per plugin update check.
  # Recommended value: 5
  timeout: 5

  # skUnity API key, required for all addons that use the skUnity service
  # You can get a free API key here: https://skunity.com/dashboard/skunity-api
  skunity-api-key: "disabled"

# format:
# addon name in lowercase:
# id: the GitHub repo name or skUnity resource ID
# service: whether the addon is from GitHub or skUnity
addons:
  skript:
    id: SkriptLang/Skript
    service: github
  skcheese:
    id: erenkarakal/SkCheese
    service: github
  hippo:
    id: Pesekjak/Hippo
    service: github
  skbee:
    id: ShaneBeee/SkBee
    service: github
  skript-reflect:
    id: SkriptLang/skript-reflect
    service: github
  skriptplus:
    id: erenkarakal/SkriptPlus
    service: github
  skreloader:
    id: 1716
    service: skunity
  skript-scoreboards:
    id: UnderscoreTud/skript-scoreboards
    service: github
  vault:
    id: MilkBowl/Vault
    service: github