name: SkriptPlus
version: '${project.version}'
main: me.eren.skriptplus.SkriptPlus
api-version: '1.17'
authors:
  - eren.

commands:
  skp:
    aliases: skriptplus
    usage: /skp
    permission: skriptplus